[package]
name = "snake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clearscreen = "1.0.9"
float-ord = "0.3.2"
rand = { version = "0.8.4", features = ["small_rng"] }
